### ISSUE TITLE
Test JACOBIN-0263-gc gives intermittent error on Windows 10

### ISSUE THREAD

**Issue by platypusguy** [texadactyl/jacotest.go#14]
When running test [JACOBIN-0263-gc](https://github.com/texadactyl/jacotest.go/tree/main/tests/JACOBIN-0263-gc), I get an intermittent error on Windows 10 running HotSpot from JDK17 (Termurin). Attached image shows the output. 

If I had to guess, it might be because the total elapsed time is zero--although the error occurring in `<init>`, which is the constructor, makes me most uncertain about my diagnosis. 

![263-error-Windows10](https://github.com/texadactyl/jacotest.go/assets/920630/f826059f-1b43-4bd0-888d-70e5be3b2750)

**Comment by texadactyl** [comment]
I'll try this when I get home on Linux

**Comment by texadactyl** [comment]
@platypusguy 

Am I supposed to install a special JDK 17 from somewhere else? If so, please furnish a URL for the download and I will try again.

Saw JDK17 (Termurin) for Windows here: [https://adoptium.net/temurin/releases/?os=windows](url) 
Is that the one?
Or this? [https://winstall.app/apps/EclipseAdoptium.Temurin.17.JDK](url)

Precise instructions are most welcome.

**Comment by texadactyl** [comment]
In any case, you were correct about the zero divisor.  JACOBIN-0263-gc function roundedPct should protect itself from zeros or near-zeros!

**Comment by texadactyl** [comment]
Function roundedPct should be protecting itself now from elapsed times that are unexpectedly small (not a bug).

Please update your local jacotest from github and try it again.

**Comment by texadactyl** [comment]
@platypusguy 
Is this now resolved in your opinion? Feel free to close if so.

**Comment by platypusguy** [comment]
Thanks for your work on this!
