### ISSUE TITLE
Retry on SQL INSERT duplicate key errors

### ISSUE THREAD

**Issue by texadactyl** [texadactyl/jacotest.go#18]
```sqlite3.go``` is affected:
* Wait 1 second.
* Get a new UTC date and time.
* Rebuild the SQL command-text.
* Rerun the SQL command.
* If it fails a 2nd time, that's fatal.

Note 1st time failure as a nonfatal error.
Note recovery in 2nd attempt as successful.

**Comment by texadactyl** [comment]
@platypusguy 
This enhancement is very difficult to verify as implemented since it is timing-dependent. However, a second pair of eyes on the ```sqlite3.go``` source code would be appreciated.

**Comment by platypusguy** [comment]
This looks good, but I should tell you that database manipulation is not an area of core competence for me. So, I could be making flattering comments that I can't defend. ;-)
I like your solution, which should conclusively solve the problem at our scale of need. I hope/trust that the changes to Jacobin itself will preclude the need for recourse to this device. We'll see!
 
Thanks again @texadactyl !
