### ISSUE TITLE
Issues raised by Om Andrew

### ISSUE THREAD

**Issue by texadactyl** [texadactyl/jacotest.go#6]
Om Richard,

I finally got some time off from all this excess vacationing and spent it happily getting into Jacotest.

Above all, thank you for this original test suite that I can run without blowing up my GitHub Actions and thereby incurring on the project home page, the dreaded, red "Failed to run properly" badge.

Here are initial thoughts and suggestions. I thought I'd send them in an email and you can break them out into tasks on GitHub if you want or if you prefer on a free instance of YouTrack. I like the latter more than GitHub b/c we can speak freely about deficiencies without making our project look deficient. Anyway, please take them in exactly the same spirit as your many thoughtful comments pointing out deficiencies and possible improvements in Jacobin.

#### Simple stuff ####

In the run reports: 
*   In markdown ```<br>``` is not a valid tag, so those tags in the run report look strange.
*  I would make the test case field fixed length, say 20 chars wide. We can always make sure that tests are distinguishable within the first 20 chars. Having it be fixed width, it's easy to scan the report for failures.
*  In the report as currently generated with -j java, after the line for negtest-runner-timeout, I get the following line:
    ```||| |```
* Finally, I would suggest that the non-Jacobin run, not be called java, as both JVMs are in theory executing Java. I think OPENJDK or just JDK are more descriptive.

#### Failed on every test ####
* When I run Jacotest against Jacobin, I get "FAILED" on every test. That appears to be b/c it can't find the Jacobin executable. I would suggest testing for the Jacobin executable before the test run. If it can't be found, then say that in the report and abort the run. There's no point running the tests after that.
* When Jacotest can't find Jacobin, it generates an empty log file for the failed test. Which I think is another reason to avoid running the tests at all if the executable can't be found.

#### Running Jacotest ####
If I copy jacobin.exe to the main Jacotest directory and juse -j jacobin on the command line, the tests run, but every Executing statement is followed by:

    *** ERROR, runnder: cmd.run(jacobin main.class) returned:

Once again, all the log files are empty, so I can't tell what's wrong.

----------------------------------------------------------------------------------------------------------------------------

Again, thank you for Jacotest. I look forward to using it regularly, once I can get it to run on my system.

Feel free to move these comments to a different forum and we can continue the dialog there, or we can carry on via email--as your preference dictates.

**Comment by texadactyl** [comment]
My lack of experience with current Windows aside, I will address all of your issues as best that I can from a nix point of view.  I will try and see if I can install Windows in a VM too.

**Comment by texadactyl** [comment]
1. The .md files are meant only to be viewed in a browser (a limitation).  Maybe, I should have gone with PDF or database generation.  Still possible.

**Comment by texadactyl** [comment]
2.  Please note that ```<br>``` and other HTML coding is permitted and used in .md files.  My use of ```<md>``` was intentional for spacing between the report title lines and the table of details.

**Comment by texadactyl** [comment]
3. "test case field fixed length, say 20 chars wide" - let me look into that.

**Comment by texadactyl** [comment]
4. "||| |" - This is intentional in order to get the 3rd column lined up inside of an .md table structure. Viewed raw, yes, it looks weird.

**Comment by texadactyl** [comment]
5. jvm name - Admittedly, I simply used the executable name as the JVM name. Lazy, perhaps. Will switch to "openjdk" for the purpose of labeling in file names and output text commentary.

**Comment by texadactyl** [comment]
6. "FAILED" on every test" -  Sorry for the unpleasant surprise! This never happened to me because the directory where the Jacobin and jacotest executables reside is defined on my system and Github Actions to be part of the PATH. This can also be done on Windows. Or, would you prefer that I look for one of the Jacobin environment variables and use it as the directory to find the Jacobin executable?  Admittedly, using the PATH is a Unix/Linux/MacOS cultural habit.

In a separate issue report, I am going to cite the lack of operational support (installation, etc.).

**Comment by texadactyl** [comment]
7. " testing for the Jacobin executable before the test run", "generates an empty log file" - agreed.  Another separate issue to write up. Thanks.

**Comment by texadactyl** [comment]
8. "*** ERROR, runnder: cmd.run(jacobin main.class) returned" - Never seen in a nix environment. Cultural issue? I'll make a go at installing Windows in a VM.

**Comment by texadactyl** [comment]
8. I need to try this on nix and Windows:

```
If I type in:

     jacotest -x -j [path to Jacobin]

I get a two-line output:

    My verison: 1.0  
    Built with: go1.20.2
```

When I do that on nix, I see this:
```
08:48:29 *** ERROR, Unrecognizable JVM parameter: /home/elkins/BASIS/bin/jacobin

Usage:  jacotest  [-h]  [-c]  [-x]  [-v]  [ -j { java | jacobin } ]

where
	-h : This display
	-x : Compile and execute all of the tests
	-v : Verbose logging
	-j : This is the JVM to use in executing all test cases.  Default: java
	-t : This is the timeout value in seconds (deadline) in executing all test cases.  Default: 60
	-c : Clean all of the .class files and .log files

My version: 1.0
Built with: go1.20.2
BuildData vcs.revision: df57ddd1b5da991ecc29d4676c3abaca0c2a988b
BuildData vcs.time: 2023-04-21T11:31:34Z
BuildData vcs.modified: false
```

Jacotest is expecting a JVM executable name, not its relative or absolute path.  Sure fix: make sure that the Jacobin executable is in a directory that is in the PATH (sorry for the broken record). 

In Windows, you can alter the PATH in a login file.  E.g. 
* Permanently - https://www.computerhope.com/issues/ch000549.htm#dospath
* Command line - https://www.computerhope.com/pathhlp.htm
* I used to do this in batch files to amend the PATH: ```PATH=JacobinIsHere;%PATH%```. 
* I had put that PATH amendment in my logon script file for Windows 7 at Citi, billions of years ago.

Lets use the C:\Users\UnkaAndoo\go\bin directory to hold our Go executables.  Ok?

**Comment by texadactyl** [comment]
9. "*** ERROR, runnder: cmd.run(jacobin main.class) returned" - Never seen in a nix environment. Cultural issue? I'll make a go at installing Windows in a VM.

**Comment by platypusguy** [comment]
Thanks for your thoughtful consideration of my comments!

I think MD is a fine format for the reports. To add blank lines in the MD file, have a look at [this](https://dev.to/rimutaka/how-to-display-multiple-blank-lines-in-markdown-20ee). I like MD, because it's simple for you to generate and easy to consume (and/or convert to other formats). I'd vote for staying with MD. 

Re the placement of the Jacobin file. That's fine if you expect in on the PATH and not by specifying the path on the command line. I'll try that and report back any problems that occur.
